### ISSUE TITLE
Bad base version bounds on some versions

### ISSUE THREAD

**Issue by lspitzner** [haskell-distributed/rank1dynamic#20]
See https://matrix.hackage.haskell.org/package/rank1dynamic

**Comment by hvr** [comment]
I just noticed that rank1dynamic-0.4.0 doesn't build on base < 4.8:

```
Configuring library for rank1dynamic-0.4.0..
Preprocessing library for rank1dynamic-0.4.0..
Building library for rank1dynamic-0.4.0..
[1 of 2] Compiling Data.Rank1Typeable ( src/Data/Rank1Typeable.hs, /tmp/matrix-worker/1503409023/dist-newstyle/build/x86_64-linux/ghc-7.8.4/rank1dynamic-0.4.0/build/Data/Rank1Typeable.o )

src/Data/Rank1Typeable.hs:166:14:
    Not in scope: ‘T.tyConFingerprint’
```

I've  revised accordingly: https://hackage.haskell.org/package/rank1dynamic-0.4.0/revisions/

**Comment by LaurentRDC** [comment]
The repository has moved and this issue is no longer relevant
